### ISSUE TITLE
Cura shutsdown on Adding Printer

### ISSUE THREAD

**Issue by TurnerTron** [Toylerrr/ElegooNeptune2Integration#2]
I drag & dropped the files into the interface & restarted the program. The Elegoo Neptune 2 popped up on the list, but upon clicking the ADD button, the program closes after a short pause. It has done this multiple times now. Any ideas?

**Comment by Toylerrr** [comment]
What version and os?

**Comment by TurnerTron** [comment]
Just downloaded the newest version today & running Windows 11.

**Comment by TurnerTron** [comment]
I managed to get my settings from another slicer so not a big deal. It keeps closing when I load certain files now too. Any idea how to go about removing the files I drag n dropped in?

**Comment by Toylerrr** [comment]
Weird, I'm on v12 and windows 11 works find for me. Glad you got something
to work for you.

You can uninstall the plugin in the plugin manager then remove the def
files from appdata

**Comment by Toylerrr** [comment]
One-off problem
